# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: bigstream_computeinverse
description: Compute the inverse of a local deformation field using Bigstream
keywords:
  - bigstream
  - inverse
  - deformation
tools:
  - "bigstream":
      description: "Tool for creating an alignment pipeline using different ITK algorithms"
      homepage: "https://github.com/JaneliaSciComp/bigstream"
      documentaton: "https://github.com/JaneliaSciComp/bigstream"
      tool_dev_url: "https://github.com/JaneliaSciComp/bigstream"
      license: "['BSD-3-Clause']"
components: []
input:
  - meta:
      type: map
      description: |
        Groovy map containing: id
  - deform_dir:
      type: directory
      description: Location of the displacement vector field
  - deform_name:
      type: string
      description: Name of the deformation transform file
  - deform_subpath:
      type: string
      description: Displacement vector subpath within the deform container
  - inv_deform_dir:
      type: directory
      description: Output directory for the inverse displacement vector field
  - inv_deform_name:
      type: string
      description: Name of the inverse deformation transform file
  - inv_deform_subpath:
      type: string
      description: Inverse displacement vector subpath
  - dask_scheduler:
      type: string
      description: Dask scheduler address
  - dask_config:
      type: file
      description: Dask configuration file (optional)
  - bigstream_cpus:
      type: integer
      description: Number of CPUs allocated to the process
  - bigstream_mem_in_gb:
      type: integer
      description: Memory in GB allocated to the process
output:
  - meta:
      type: map
      description: |
        Groovy map containing: id
  - full_deform_dir:
      type: string
      description: Full resolved path to the deformation directory
  - deform_name:
      type: string
      description: Name of the deformation transform file
  - deform_subpath:
      type: string
      description: Displacement vector subpath
  - full_inv_deform_dir:
      type: string
      description: Full resolved path to the inverse deformation directory
  - inv_deform_name:
      type: string
      description: Name of the inverse deformation transform file
  - inv_deform_subpath:
      type: string
      description: Inverse displacement vector subpath
authors:
  - "@cgoina"
  - "@fleishmang"
