# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: bigstream_registration
description: Runs a registration pipeline using Bigstream on a Dask cluster
keywords:
  - registration
  - bigstream
  - dask
components:
  - janelia/bigstream/globalalign
  - janelia/bigstream/localalign
  - janelia/bigstream/deform
  - janelia/dask_start
  - janelia/dask_stop
